### ISSUE TITLE
[Effect Fix] The ever increasing amount of effects of Quick Cast .-.

### ISSUE THREAD

**Issue by Clauvin** [DioBal/TheGartic#49]
![image](https://user-images.githubusercontent.com/5853416/163729690-0b84dc3f-1ad2-4831-8a91-0853f3dad1bc.png)

The image above is what happens when the same Quick Cast card is used twice in battle: it seems that instead of creating or using the same set of two card choices, it adds more card choices to its set. The effect is cumulative, as the scrolling bar at the image below demonstrates:

![image](https://user-images.githubusercontent.com/5853416/163729727-4c6aa038-2c1b-48dc-aae6-e5f0b10e9079.png)

The effect is cumulative to the same instance of a card, not between different Quick Cast cards.

It shows up in the latest merged codebase (https://github.com/DioBal/TheGartic/commit/40180610040603f1cab27ba271f1adbcd2e4dc3b)

**Comment by bkerns724** [comment]
Someone fixed it
