### ISSUE TITLE
[Description Fix] Celestial Crafting's power does not have a description

### ISSUE THREAD

**Issue by Clauvin** [DioBal/TheGartic#50]
![image](https://user-images.githubusercontent.com/5853416/163729837-dc839d32-9b5b-4c35-830c-a654833fd0b4.png)

Currently on the latest merged codebase (https://github.com/DioBal/TheGartic/commit/40180610040603f1cab27ba271f1adbcd2e4dc3b).

**Comment by bkerns724** [comment]
It is fixed
