### ISSUE TITLE
[Effect Fix] Tall Grass does not reduce its cost permanently when drawn

### ISSUE THREAD

**Issue by Clauvin** [DioBal/TheGartic#86]
![image](https://user-images.githubusercontent.com/5853416/175395483-276cc3fe-d2ec-49c3-abd8-d5001f48ed68.png)

As the title says, Tall Grass does not reduce its cost when drawn, at all.

It shows up in the latest merged codebase (https://github.com/DioBal/TheGartic/commit/a53d7ecfea84f93e10ab14e2603610c9fd42140e)

**Comment by bkerns724** [comment]
Someone has fixed this
