### ISSUE TITLE
[Description Fix] Wisdow Stance does not show its description

### ISSUE THREAD

**Issue by Clauvin** [DioBal/TheGartic#87]
![image](https://user-images.githubusercontent.com/5853416/175796720-4c01432a-e693-4b8b-ba9c-8811f2ded707.png)

Wisdow Stance does not have a description. That happens both as above, when the player has the stance...

![image](https://user-images.githubusercontent.com/5853416/175796750-17550505-cb0e-4d7d-bea5-94cab8033177.png)

...and when the player hovers on the card that gives the Stance.

It shows up in the latest merged codebase (https://github.com/DioBal/TheGartic/commit/a53d7ecfea84f93e10ab14e2603610c9fd42140e)

**Comment by Mindbomber2** [comment]
Fixed with #103
